spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:finflowbackend}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: false

  jpa:
    show-sql: true